//
// Copyright (c) 2015 DudeTeam. All rights reserved.
//

/**
 * A point represents either an input or an output in a block, it has a name and a value type
 * A point can also have one or many references to other points:
 *    - The outbound point must be an output
 *    - The outbound point value type must be accepted by the inbound point
 *    - The outbound point must have a back reference to this point
 * Example for an input point:
 * {
 *      "cgBlock": "1", // The unique identifier to the block, required
 *      "cgName": "sum a", // The block input name, required
 *      "cgValueType": "Number", // The point value type, required
 *      "cgValue": 32 // The point value for an input, not required
 * }
 * Example for an output point:
 * {
 *      "cgBlock": "1", // The unique identifier to the block, required
 *      "cgName": "result", // The block output name, required
 *      "cgValueType": "Number", // The point value type, required
 *      // For an output, "cgValue" should be generated by the block and read only
 * }
 * @param {dudeGraph.Block} cgBlock - The block this point refers to
 * @param {Object} data - The point data
 * @param {String} data.cgName - The point data
 * @param {String} [data.cgValue=null] - The point data
 * @param {String} [data.cgValueType=null] - The point data
 * @param {String} [data.cgTemplate=null] - The point data
 * @param {String} [data.singleConnection=null] - The point data
 * @param {Boolean} isOutput - True if this point is an output, False for an input
 * @param {String} pointType - The type of this point represented as a string
 * @class
 */
dudeGraph.Point = function (cgBlock, data, isOutput, pointType) {

    /**
     * The graph of the block
     * @type {dudeGraph.Graph}
     */
    Object.defineProperty(this, "cgGraph", {
        get: function () {
            return this._cgGraph;
        }.bind(this)
    });
    this._cgGraph = cgBlock.cgGraph;

    /**
     * The type of this point represented as a string, default to "Point".
     */
    Object.defineProperty(this, "pointType", {
        get: function () {
            return this._pointType;
        }.bind(this)
    });
    this._pointType = this.className;

    /**
     * The block it belongs to
     * @type {dudeGraph.Block}
     */
    Object.defineProperty(this, "cgBlock", {
        get: function () {
            return this._cgBlock;
        }.bind(this)
    });
    this._cgBlock = cgBlock;

    /**
     * The block input/output name
     * @type {String}
     */
    Object.defineProperty(this, "cgName", {
        get: function () {
            return this._cgName;
        }.bind(this)
    });
    this._cgName = data.cgName || this._pointType;

    /**
     * Point type, True if this point is an output, False for an input
     * @type {Boolean}
     */
    Object.defineProperty(this, "isOutput", {
        get: function () {
            return this._isOutput;
        }.bind(this)
    });
    this._isOutput = isOutput;

    /**
     * Connections from/to this point
     * @type {Array<dudeGraph.Connection>}
     */
    Object.defineProperty(this, "cgConnections", {
        get: function () {
            return this._cgConnections;
        }.bind(this)
    });
    this._cgConnections = [];

    /**
     * Whether this point accept one or several connections.
     * @type {Boolean}
     */
    Object.defineProperty(this, "singleConnection", {
        get: function () {
            return this._singleConnection;
        }.bind(this),
        set: function (singleConnection) {
            this._singleConnection = singleConnection;
        }.bind(this)
    });
    this._singleConnection = _.isUndefined(data.singleConnection) ? true : data.singleConnection;

    /**
     * The name of the template type used (from parent block).
     * @type {String|null}
     */
    Object.defineProperty(this, "cgTemplate", {
        get: function () {
            return this._cgTemplate;
        }.bind(this)
    });
    this._cgTemplate = data.cgTemplate || null;

    /**
     * The point current value type
     * Example: Number (Yellow color)
     * @type {String}
     * @emit "cg-point-value-type-change" {dudeGraph.Point} {Object} {Object}
     */
    Object.defineProperty(this, "cgValueType", {
        get: function () {
            return this._cgValueType;
        }.bind(this),
        set: function (cgValueType) {
            var old = this._cgValueType;
            this._cgValueType = cgValueType;
            this._cgGraph.emit("cg-point-value-type-change", this, old, cgValueType);
        }.bind(this)
    });
    this._cgValueType = data.cgValueType;
    if (_.isUndefined(data.cgValueType)) {
        throw new Error("Cannot create the point `" + this._cgName + "` in block `" + this._cgBlock.cgId +
            "` without specifying a value type");
    }

    /**
     * The point current value
     * @type {Object|null}
     * @emit "cg-point-value-change" {dudeGraph.Point} {Object} {Object}
     */
    Object.defineProperty(this, "cgValue", {
        configurable: true,
        get: function () {
            return this._cgValue;
        }.bind(this),
        set: function (cgValue) {
            if (cgValue !== null && !this.acceptValue(cgValue)) {
                throw new Error("Cannot set `cgValue`: Point `" + this._cgName + "` cannot accept more than " +
                    "one connection");
            }
            if (this._cgGraph.canAssign(cgValue, this._cgValueType)) {
                var oldCgValue = this._cgValue;
                this._cgValue = cgValue;
                this._cgBlock.pointValueChanged(this, cgValue, oldCgValue);
                this._cgGraph.emit("cg-point-value-change", this, oldCgValue, cgValue);
            } else {
                throw new Error("Invalid value `" + String(cgValue) +
                    "` for `" + this._cgValueType + "` in `" + this._cgName + "`");
            }
        }.bind(this)
    });
    if (isOutput && data.cgValue !== null && !_.isUndefined(data.cgValue)) {
        throw new Error("Cannot create output point `" + this._cgName + "` in block `" +
            this._cgBlock.cgId + "` with a value.");
    }
    this._cgValue = data.cgValue || null;
};

dudeGraph.Point.prototype = _.create(Object.prototype, {
    "constructor": dudeGraph.Point,
    "className": "Point"
});

/**
 * Returns whether this cgPoint is empty (no cgValue)
 * @returns {Boolean}
 */
dudeGraph.Point.prototype.empty = function () {
    return this._cgValue === null;
};

//noinspection JSUnusedLocalSymbols
/**
 * Returns whether this cgPoint accepts a connection if there is room to the given cgPoint
 * @param {dudeGraph.Point} cgPoint
 * @returns {Boolean}
 */
dudeGraph.Point.prototype.acceptConnect = function (cgPoint) {
    return !this._singleConnection || (this._cgConnections.length === 0 && this._cgValue === null);
};

//noinspection JSUnusedLocalSymbols
/**
 * Returns whether this cgPoint accepts a cgValue
 * @param {Object} [cgValue]
 * @returns {Boolean}
 */
dudeGraph.Point.prototype.acceptValue = function (cgValue) {
    return !this._singleConnection || this._cgConnections.length === 0;
};

/**
 * Adds a connection from this cgPoint to the given cgPoint
 * @param {dudeGraph.Point} cgPoint
 * @return {dudeGraph.Connection}
 */
dudeGraph.Point.prototype.connect = function (cgPoint) {
    if (this._isOutput) {
        return this._cgGraph.connectPoints(this, cgPoint);
    } else {
        return this._cgGraph.connectPoints(cgPoint, this);
    }
};

/**
 * Removes the connection between this cgPoint and the given cgPoint
 * @param {dudeGraph.Point} cgPoint
 */
dudeGraph.Point.prototype.disconnect = function (cgPoint) {
    if (this._isOutput) {
        return this._cgGraph.disconnectPoints(this, cgPoint);
    } else {
        return this._cgGraph.disconnectPoints(cgPoint, this);
    }
};

/**
 * Returns a copy of this point
 * @param {dudeGraph.Block} cgBlock - The block on which this cloned point will be attached to
 * @return {dudeGraph.Point}
 */
dudeGraph.Point.prototype.clone = function (cgBlock) {
    return new this.constructor(cgBlock, {
        cgName: this._cgName,
        cgValueType: this._cgValueType,
        cgValue: this._cgValue
    }, this._isOutput);
};